// get_concept — fetch a full concept document from this origin's OKF bundle.
// The id->url map is embedded at build time (content-addressed via tool_sha256).
var CONCEPTS = {"OKF-SPEC.md":"/knowledge/OKF-SPEC.md","architecture/overview.md":"/knowledge/architecture/overview.md","casos-reales.md":"/knowledge/casos-reales.md","contracts/agents-context-rule.md":"/knowledge/contracts/agents-context-rule.md","contracts/assemble-context.md":"/knowledge/contracts/assemble-context.md","contracts/benchmark-gates.md":"/knowledge/contracts/benchmark-gates.md","contracts/changelog-gate.md":"/knowledge/contracts/changelog-gate.md","contracts/check-agent-wiring.md":"/knowledge/contracts/check-agent-wiring.md","contracts/check-graph.md":"/knowledge/contracts/check-graph.md","contracts/commit-message-gate.md":"/knowledge/contracts/commit-message-gate.md","contracts/export-gate-contract.md":"/knowledge/contracts/export-gate-contract.md","contracts/init-project.md":"/knowledge/contracts/init-project.md","contracts/lint-ascii.md":"/knowledge/contracts/lint-ascii.md","contracts/perimeter-gate.md":"/knowledge/contracts/perimeter-gate.md","contracts/route-message.md":"/knowledge/contracts/route-message.md","contracts/rules-gate.md":"/knowledge/contracts/rules-gate.md","contracts/sample_task.md":"/knowledge/contracts/sample_task.md","contracts/skills-gate.md":"/knowledge/contracts/skills-gate.md","contracts/ux-page-gate.md":"/knowledge/contracts/ux-page-gate.md","contracts/validate-article.md":"/knowledge/contracts/validate-article.md","contracts/validate-okf.md":"/knowledge/contracts/validate-okf.md","contracts/validate-payment-limit.md":"/knowledge/contracts/validate-payment-limit.md","contracts/validate-rules.md":"/knowledge/contracts/validate-rules.md","contracts/validate-specs.md":"/knowledge/contracts/validate-specs.md","contracts/validate-user-record.md":"/knowledge/contracts/validate-user-record.md","contracts/versioning-plantilla.md":"/knowledge/contracts/versioning-plantilla.md","data_models/agent_wiring.md":"/knowledge/data_models/agent_wiring.md","data_models/border_rules.md":"/knowledge/data_models/border_rules.md","data_models/commit_message_contract.md":"/knowledge/data_models/commit_message_contract.md","data_models/editorial_style.md":"/knowledge/data_models/editorial_style.md","data_models/mcp_registry.md":"/knowledge/data_models/mcp_registry.md","data_models/message_routing.md":"/knowledge/data_models/message_routing.md","data_models/payment_limits.md":"/knowledge/data_models/payment_limits.md","data_models/users_table.md":"/knowledge/data_models/users_table.md","data_models/ux_page_contract.md":"/knowledge/data_models/ux_page_contract.md","data_models/workflow_policy.md":"/knowledge/data_models/workflow_policy.md","metodologia-ejecucion.md":"/knowledge/metodologia-ejecucion.md","plantilla-upgrade.md":"/knowledge/plantilla-upgrade.md","rule-contract-spec.md":"/knowledge/rule-contract-spec.md","validacion.md":"/knowledge/validacion.md"};
registerTool({
  name: "get_concept",
  description: "Fetch the full markdown of a knowledge concept by id (as returned by search_knowledge / list_concepts).",
  inputSchema: { type: "object", properties: { id: { type: "string", description: "concept id, e.g. policies/refunds.md" } }, required: ["id"] },
  handler: async function (args) {
    var url = CONCEPTS[args.id];
    if (!url) throw new Error("unknown concept id: " + args.id);
    var r = await host.fetchOrigin(url);
    if (r.status !== 200) throw new Error("fetch failed: HTTP " + r.status);
    return { id: args.id, markdown: r.body };
  }
});
